# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-09 06:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Codigo',
            fields=[
                ('idcodigo', models.IntegerField(primary_key=True, serialize=False)),
                ('enlace', models.CharField(max_length=500)),
                ('codigodes', models.CharField(max_length=1000)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'codigo',
                'managed': True,
            },
        ),
    ]
